const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

const users = [
  { name: 'Ravi Shankar',    email: 'ravi.owner@rentease.in',   role: 'OWNER',  avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ravi' },
  { name: 'Priya Mehta',     email: 'priya.owner@rentease.in',  role: 'OWNER',  avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=priya' },
  { name: 'Arjun Reddy',     email: 'arjun.owner@rentease.in',  role: 'OWNER',  avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=arjun' },
  { name: 'Sunita Rao',      email: 'sunita.owner@rentease.in', role: 'OWNER',  avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sunita' },
  { name: 'Karthik Iyer',    email: 'karthik.owner@rentease.in',role: 'OWNER',  avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=karthik' },
  { name: 'Ananya Krishnan', email: 'ananya.tenant@rentease.in',role: 'TENANT', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ananya' },
  { name: 'Rohit Verma',     email: 'rohit.tenant@rentease.in', role: 'TENANT', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=rohit' },
  { name: 'Meera Nair',      email: 'meera.tenant@rentease.in', role: 'TENANT', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=meera' },
  { name: 'Platform Admin',  email: 'admin@rentease.in',        role: 'ADMIN',  avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=admin' },
];

// Cloudinary demo images per type
const IMG = {
  APARTMENT: ['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800','https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800'],
  VILLA:     ['https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800','https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800'],
  STUDIO:    ['https://images.unsplash.com/photo-1540518614846-7eded433c457?w=800','https://images.unsplash.com/photo-1574362848149-11496d93a7c7?w=800'],
  INDEPENDENT_HOUSE: ['https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800','https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800'],
  PG:        ['https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800','https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800'],
};

const properties = [
  // ── HYDERABAD (25) ──────────────────────────────────────────────────────────
  { title:'Spacious 2BHK in Kondapur', city:'Hyderabad', area:'Kondapur', address:'Plot 14, Sri Nagar Colony, Kondapur', rent:22000, deposit:66000, bedrooms:2, bathrooms:2, furnished:'SEMI_FURNISHED', propertyType:'APARTMENT', floorArea:1050, amenities:['Wi-Fi','Power Backup','Security','Parking'], description:'Well-maintained 2BHK apartment in a gated community near Hitec City. Close to metro and major IT parks.', status:'AVAILABLE' },
  { title:'1BHK in Gachibowli IT Corridor', city:'Hyderabad', area:'Gachibowli', address:'Block C, Manjeera Trinity, Gachibowli', rent:16000, deposit:48000, bedrooms:1, bathrooms:1, furnished:'FURNISHED', propertyType:'APARTMENT', floorArea:620, amenities:['Wi-Fi','AC','Gym','Power Backup','CCTV'], description:'Ready-to-move furnished 1BHK walking distance to major IT companies in Gachibowli.', status:'AVAILABLE' },
  { title:'3BHK Independent House in Miyapur', city:'Hyderabad', area:'Miyapur', address:'8-2-45, Srinivasa Nagar, Miyapur', rent:24000, deposit:72000, bedrooms:3, bathrooms:2, furnished:'UNFURNISHED', propertyType:'INDEPENDENT_HOUSE', floorArea:1300, amenities:['Parking','Garden','Borewell','Terrace'], description:'Independent 3BHK house with terrace access in a peaceful residential colony near metro.', status:'AVAILABLE' },
  { title:'Luxury 4BHK Villa in Jubilee Hills', city:'Hyderabad', area:'Jubilee Hills', address:'Road No. 36, Jubilee Hills', rent:75000, deposit:225000, bedrooms:4, bathrooms:4, furnished:'FURNISHED', propertyType:'VILLA', floorArea:3200, amenities:['Private Pool','Home Theatre','Smart Home','Security','Parking'], description:'Ultra-premium 4BHK villa in Hyderabad\'s most prestigious address. Fully automated smart home.', status:'AVAILABLE' },
  { title:'Studio Apartment in Madhapur', city:'Hyderabad', area:'Madhapur', address:'Plot 92, Aditya Enclave, Madhapur', rent:14000, deposit:42000, bedrooms:1, bathrooms:1, furnished:'FURNISHED', propertyType:'STUDIO', floorArea:400, amenities:['Wi-Fi','AC','Security','Power Backup'], description:'Modern studio apartment in the heart of Hyderabad\'s IT district — ideal for solo professionals.', status:'AVAILABLE' },
  { title:'2BHK Flat in Kukatpally', city:'Hyderabad', area:'Kukatpally', address:'KPHB Phase 4, Kukatpally', rent:18000, deposit:54000, bedrooms:2, bathrooms:2, furnished:'SEMI_FURNISHED', propertyType:'APARTMENT', floorArea:980, amenities:['Parking','Lift','Security','Power Backup'], description:'Affordable 2BHK in KPHB, one of Hyderabad\'s most sought-after residential hubs.', status:'AVAILABLE' },
  { title:'3BHK in Banjara Hills', city:'Hyderabad', area:'Banjara Hills', address:'Road No. 12, Banjara Hills', rent:45000, deposit:135000, bedrooms:3, bathrooms:3, furnished:'FURNISHED', propertyType:'APARTMENT', floorArea:1800, amenities:['AC','Gym','Parking','Security','Clubhouse'], description:'Premium 3BHK in upscale Banjara Hills with modern interiors and full amenities.', status:'AVAILABLE' },
  { title:'1BHK Studio near HITEC City', city:'Hyderabad', area:'HITEC City', address:'Cyber Pearl Complex, HITEC City', rent:15000, deposit:30000, bedrooms:1, bathrooms:1, furnished:'FURNISHED', propertyType:'STUDIO', floorArea:380, amenities:['Wi-Fi','AC','CCTV','Power Backup'], description:'Compact studio ideal for IT professionals. Walk to major tech campuses.', status:'AVAILABLE' },
  { title:'4BHK Villa in Manikonda', city:'Hyderabad', area:'Manikonda', address:'Villa 8, Green Valley, Manikonda', rent:55000, deposit:165000, bedrooms:4, bathrooms:3, furnished:'SEMI_FURNISHED', propertyType:'VILLA', floorArea:2400, amenities:['Garden','Parking','Security','Power Backup'], description:'Spacious villa with private garden in a quiet gated community near Financial District.', status:'AVAILABLE' },
  { title:'PG in Ameerpet', city:'Hyderabad', area:'Ameerpet', address:'Near Metro Station, Ameerpet', rent:9000, deposit:18000, bedrooms:1, bathrooms:1, furnished:'FURNISHED', propertyType:'PG', floorArea:200, amenities:['Wi-Fi','Meals','Laundry','CCTV'], description:'Affordable PG accommodation near Ameerpet metro. Ideal for students and working professionals.', status:'AVAILABLE' },
  { title:'2BHK in Secunderabad', city:'Hyderabad', area:'Secunderabad', address:'SD Road, Secunderabad', rent:20000, deposit:60000, bedrooms:2, bathrooms:2, furnished:'UNFURNISHED', propertyType:'APARTMENT', floorArea:1100, amenities:['Parking','Security','Lift'], description:'Spacious 2BHK near Secunderabad railway station. Well-connected to all parts of the city.', status:'AVAILABLE' },
  { title:'3BHK in Nallagandla', city:'Hyderabad', area:'Nallagandla', address:'Aparna Constructions, Nallagandla', rent:28000, deposit:84000, bedrooms:3, bathrooms:2, furnished:'SEMI_FURNISHED', propertyType:'APARTMENT', floorArea:1550, amenities:['Gym','Pool','Security','Parking','Power Backup'], description:'Modern township flat with club house and swimming pool access. Near Outer Ring Road.', status:'AVAILABLE' },
  { title:'Independent House in LB Nagar', city:'Hyderabad', area:'LB Nagar', address:'Street 4, LB Nagar Colony', rent:17000, deposit:51000, bedrooms:2, bathrooms:1, furnished:'UNFURNISHED', propertyType:'INDEPENDENT_HOUSE', floorArea:850, amenities:['Parking','Garden','Borewell'], description:'Ground floor independent house with parking and garden. Near LB Nagar metro.', status:'AVAILABLE' },
  { title:'1BHK in Uppal', city:'Hyderabad', area:'Uppal', address:'Uppal Main Road, Near Metro', rent:11000, deposit:33000, bedrooms:1, bathrooms:1, furnished:'SEMI_FURNISHED', propertyType:'APARTMENT', floorArea:520, amenities:['Parking','Security'], description:'Budget 1BHK near Uppal metro station. Good connectivity to IT corridor.', status:'AVAILABLE' },
  { title:'2BHK in Attapur', city:'Hyderabad', area:'Attapur', address:'Paradise Colony, Attapur', rent:16500, deposit:49500, bedrooms:2, bathrooms:2, furnished:'SEMI_FURNISHED', propertyType:'APARTMENT', floorArea:900, amenities:['Lift','Security','Power Backup'], description:'Well-ventilated 2BHK near Mehdipatnam junction. Good for families.', status:'AVAILABLE' },
  { title:'3BHK in Kompally', city:'Hyderabad', area:'Kompally', address:'Suchitra Circle, Kompally', rent:22000, deposit:66000, bedrooms:3, bathrooms:2, furnished:'UNFURNISHED', propertyType:'INDEPENDENT_HOUSE', floorArea:1400, amenities:['Parking','Terrace','Borewell'], description:'Quiet neighbourhood 3BHK with terrace garden. Close to Kompally schools and hospitals.', status:'AVAILABLE' },
  { title:'Studio in Tolichowki', city:'Hyderabad', area:'Tolichowki', address:'Tolichowki Main Road', rent:12000, deposit:24000, bedrooms:1, bathrooms:1, furnished:'FURNISHED', propertyType:'STUDIO', floorArea:350, amenities:['Wi-Fi','AC','CCTV'], description:'Fully furnished studio near Tolichowki junction. Easy access to Film Nagar and Banjara Hills.', status:'RENTED' },
  { title:'2BHK in Dilsukhnagar', city:'Hyderabad', area:'Dilsukhnagar', address:'Near Metro, Dilsukhnagar', rent:15000, deposit:45000, bedrooms:2, bathrooms:1, furnished:'SEMI_FURNISHED', propertyType:'APARTMENT', floorArea:820, amenities:['Parking','Security','Lift'], description:'Affordable 2BHK steps from Dilsukhnagar metro. Good for families.', status:'AVAILABLE' },
  { title:'4BHK Penthouse in Kokapet', city:'Hyderabad', area:'Kokapet', address:'Prestige Lakeside Habitat, Kokapet', rent:90000, deposit:270000, bedrooms:4, bathrooms:4, furnished:'FURNISHED', propertyType:'APARTMENT', floorArea:3500, amenities:['Private Terrace','Pool','Gym','Smart Home','Concierge'], description:'Breathtaking penthouse with panoramic views of Gandipet Lake. Ultra-luxury living.', status:'AVAILABLE' },
  { title:'1BHK in Begumpet', city:'Hyderabad', area:'Begumpet', address:'Raj Bhavan Road, Begumpet', rent:18000, deposit:54000, bedrooms:1, bathrooms:1, furnished:'FURNISHED', propertyType:'APARTMENT', floorArea:580, amenities:['AC','Parking','Security','Lift'], description:'Well-located 1BHK in central Begumpet near airport metro line.', status:'AVAILABLE' },
  { title:'3BHK in Shamirpet', city:'Hyderabad', area:'Shamirpet', address:'Shamirpet Lake Road', rent:19000, deposit:57000, bedrooms:3, bathrooms:2, furnished:'UNFURNISHED', propertyType:'INDEPENDENT_HOUSE', floorArea:1600, amenities:['Garden','Parking','Borewell','Terrace'], description:'Serene 3BHK near Shamirpet Lake. Perfect for families wanting a green environment.', status:'AVAILABLE' },
  { title:'2BHK in Alwal', city:'Hyderabad', area:'Alwal', address:'Alwal Cantonment Area', rent:14000, deposit:42000, bedrooms:2, bathrooms:1, furnished:'UNFURNISHED', propertyType:'APARTMENT', floorArea:780, amenities:['Parking','Security'], description:'Affordable 2BHK near Alwal. Good for government employees and defence personnel.', status:'AVAILABLE' },
  { title:'PG in Madhapur', city:'Hyderabad', area:'Madhapur', address:'Madhapur Main Road, Near Cyber Towers', rent:10500, deposit:21000, bedrooms:1, bathrooms:1, furnished:'FURNISHED', propertyType:'PG', floorArea:240, amenities:['Wi-Fi','Meals','AC','Laundry'], description:'Premium PG accommodation with all meals included. 5 min walk to Cyber Towers.', status:'AVAILABLE' },
  { title:'Villa in Shankarpally', city:'Hyderabad', area:'Shankarpally', address:'Shankarpally Road, ORR Exit 14', rent:38000, deposit:114000, bedrooms:3, bathrooms:3, furnished:'SEMI_FURNISHED', propertyType:'VILLA', floorArea:2200, amenities:['Garden','Parking','Power Backup','Security'], description:'Peaceful villa on the outskirts of Hyderabad near ORR. Surrounded by greenery.', status:'AVAILABLE' },
  { title:'2BHK in Chandanagar', city:'Hyderabad', area:'Chandanagar', address:'Chandanagar Colony, Near BHEL', rent:17000, deposit:51000, bedrooms:2, bathrooms:2, furnished:'SEMI_FURNISHED', propertyType:'APARTMENT', floorArea:950, amenities:['Parking','Lift','Security','Power Backup'], description:'Well-maintained 2BHK near BHEL township. Good for BHEL employees and IT professionals.', status:'AVAILABLE' },

  // ── BANGALORE (25) ──────────────────────────────────────────────────────────
  { title:'Modern Studio near Indiranagar Metro', city:'Bangalore', area:'Indiranagar', address:'12/3 HAL 2nd Stage, Indiranagar', rent:18000, deposit:54000, bedrooms:1, bathrooms:1, furnished:'FURNISHED', propertyType:'STUDIO', floorArea:480, amenities:['Wi-Fi','AC','Gym','CCTV'], description:'Fully furnished studio steps from Indiranagar metro. Ideal for working professionals.', status:'AVAILABLE' },
  { title:'3BHK Villa in Whitefield', city:'Bangalore', area:'Whitefield', address:'Rainbow Villas, EPIP Zone, Whitefield', rent:42000, deposit:126000, bedrooms:3, bathrooms:3, furnished:'FURNISHED', propertyType:'VILLA', floorArea:1900, amenities:['Wi-Fi','AC','Parking','Garden','Power Backup','Security'], description:'Luxurious 3BHK villa with private garden in premium gated community near ITPL.', status:'AVAILABLE' },
  { title:'3BHK in Koramangala 5th Block', city:'Bangalore', area:'Koramangala', address:'34, 5th Block, Koramangala', rent:55000, deposit:165000, bedrooms:3, bathrooms:2, furnished:'SEMI_FURNISHED', propertyType:'APARTMENT', floorArea:1400, amenities:['Parking','Power Backup','Security','Wi-Fi'], description:'Large 3BHK in Bangalore\'s most sought-after residential and commercial locality.', status:'UNDER_REVIEW' },
  { title:'PG Studio in HSR Layout', city:'Bangalore', area:'HSR Layout', address:'22, 7th Sector, HSR Layout', rent:12000, deposit:24000, bedrooms:1, bathrooms:1, furnished:'FURNISHED', propertyType:'PG', floorArea:320, amenities:['Wi-Fi','Meals','Laundry','Housekeeping'], description:'Fully serviced PG accommodation with meals included. Single occupancy available immediately.', status:'AVAILABLE' },
  { title:'2BHK in Electronic City Phase 1', city:'Bangalore', area:'Electronic City', address:'Neeladri Road, Electronic City Phase 1', rent:20000, deposit:60000, bedrooms:2, bathrooms:2, furnished:'SEMI_FURNISHED', propertyType:'APARTMENT', floorArea:1050, amenities:['Parking','Gym','Pool','Security','Power Backup'], description:'Tech-hub living! 2BHK in gated society minutes from Infosys and Wipro campuses.', status:'AVAILABLE' },
  { title:'1BHK in Marathahalli', city:'Bangalore', area:'Marathahalli', address:'Outer Ring Road, Marathahalli', rent:16000, deposit:48000, bedrooms:1, bathrooms:1, furnished:'FURNISHED', propertyType:'APARTMENT', floorArea:560, amenities:['Wi-Fi','AC','Security','CCTV'], description:'Centrally located 1BHK on ORR near major IT parks and ISRO layout.', status:'AVAILABLE' },
  { title:'4BHK Penthouse in Sadashivanagar', city:'Bangalore', area:'Sadashivanagar', address:'Windsor Manor Road, Sadashivanagar', rent:120000, deposit:360000, bedrooms:4, bathrooms:4, furnished:'FURNISHED', propertyType:'APARTMENT', floorArea:4200, amenities:['Private Terrace','Home Theatre','Wine Cellar','Security','Concierge'], description:'Bangalore\'s most exclusive penthouse address. Ultra-luxury living in heritage locality.', status:'AVAILABLE' },
  { title:'2BHK in JP Nagar 7th Phase', city:'Bangalore', area:'JP Nagar', address:'24th Cross, JP Nagar 7th Phase', rent:22000, deposit:66000, bedrooms:2, bathrooms:2, furnished:'SEMI_FURNISHED', propertyType:'APARTMENT', floorArea:1080, amenities:['Parking','Lift','Security','Power Backup'], description:'Peaceful 2BHK in well-established JP Nagar. Close to NICE road and metro corridor.', status:'AVAILABLE' },
  { title:'1BHK in Yelahanka', city:'Bangalore', area:'Yelahanka', address:'New Town, Yelahanka', rent:13000, deposit:39000, bedrooms:1, bathrooms:1, furnished:'SEMI_FURNISHED', propertyType:'APARTMENT', floorArea:540, amenities:['Parking','Security'], description:'Budget 1BHK near Yelahanka Air Force Station. Good connectivity to North Bangalore IT parks.', status:'AVAILABLE' },
  { title:'3BHK Independent House in Rajajinagar', city:'Bangalore', area:'Rajajinagar', address:'1st Block, Rajajinagar', rent:35000, deposit:105000, bedrooms:3, bathrooms:2, furnished:'UNFURNISHED', propertyType:'INDEPENDENT_HOUSE', floorArea:1700, amenities:['Parking','Garden','Terrace','Borewell'], description:'Classic independent house in old Bangalore\'s premium locality. Excellent civic infrastructure.', status:'AVAILABLE' },
  { title:'2BHK in Bellandur', city:'Bangalore', area:'Bellandur', address:'Purva Fountain Square, Bellandur', rent:28000, deposit:84000, bedrooms:2, bathrooms:2, furnished:'FURNISHED', propertyType:'APARTMENT', floorArea:1150, amenities:['Gym','Pool','Clubhouse','Parking','Security'], description:'Premium township 2BHK with resort-style amenities. Walking distance to Wipro and SAP labs.', status:'AVAILABLE' },
  { title:'Studio in BTM Layout', city:'Bangalore', area:'BTM Layout', address:'2nd Stage, BTM Layout', rent:14000, deposit:28000, bedrooms:1, bathrooms:1, furnished:'FURNISHED', propertyType:'STUDIO', floorArea:390, amenities:['Wi-Fi','AC','CCTV'], description:'Compact studio in the heart of BTM. Surrounded by cafes, malls, and startup offices.', status:'AVAILABLE' },
  { title:'4BHK Villa in Sarjapur Road', city:'Bangalore', area:'Sarjapur', address:'Sobha Dream Acres, Sarjapur Road', rent:65000, deposit:195000, bedrooms:4, bathrooms:4, furnished:'FURNISHED', propertyType:'VILLA', floorArea:3100, amenities:['Pool','Gym','Garden','Smart Home','Security','Parking'], description:'Luxury 4BHK villa in one of Bangalore\'s largest gated communities. Premium lifestyle.', status:'AVAILABLE' },
  { title:'2BHK in Jayanagar 4th Block', city:'Bangalore', area:'Jayanagar', address:'4th Block, Jayanagar', rent:30000, deposit:90000, bedrooms:2, bathrooms:2, furnished:'SEMI_FURNISHED', propertyType:'APARTMENT', floorArea:1100, amenities:['Lift','Parking','Power Backup','Security'], description:'Well-maintained 2BHK in one of Bangalore\'s most premium and planned localities.', status:'AVAILABLE' },
  { title:'PG near Manyata Tech Park', city:'Bangalore', area:'Hebbal', address:'Manyata Embassy Business Park Road, Hebbal', rent:11000, deposit:22000, bedrooms:1, bathrooms:1, furnished:'FURNISHED', propertyType:'PG', floorArea:280, amenities:['Wi-Fi','Meals','Laundry','AC'], description:'Premium PG near Manyata Tech Park. Shuttle service to major IT campuses available.', status:'AVAILABLE' },
  { title:'3BHK in Hennur Road', city:'Bangalore', area:'Hennur', address:'Prestige Tranquility, Hennur Road', rent:32000, deposit:96000, bedrooms:3, bathrooms:3, furnished:'FURNISHED', propertyType:'APARTMENT', floorArea:1620, amenities:['Pool','Gym','Clubhouse','Security','Parking','Power Backup'], description:'Gated community 3BHK with excellent amenities near Hennur Road junction.', status:'AVAILABLE' },
  { title:'1BHK in Banashankari', city:'Bangalore', area:'Banashankari', address:'3rd Stage, Banashankari', rent:15000, deposit:45000, bedrooms:1, bathrooms:1, furnished:'SEMI_FURNISHED', propertyType:'APARTMENT', floorArea:580, amenities:['Parking','Security','Lift'], description:'Good value 1BHK in south Bangalore\'s prime residential area. Metro connectivity.', status:'AVAILABLE' },
  { title:'2BHK in Frazer Town', city:'Bangalore', area:'Frazer Town', address:'Mosque Road, Frazer Town', rent:27000, deposit:81000, bedrooms:2, bathrooms:2, furnished:'FURNISHED', propertyType:'APARTMENT', floorArea:1000, amenities:['AC','Parking','Security','Intercom'], description:'Charming 2BHK in cosmopolitan Frazer Town. Near Ulsoor Lake and central Bangalore.', status:'AVAILABLE' },
  { title:'3BHK in Kanakapura Road', city:'Bangalore', area:'Kanakapura Road', address:'Prestige Falcon City, Kanakapura Road', rent:38000, deposit:114000, bedrooms:3, bathrooms:3, furnished:'SEMI_FURNISHED', propertyType:'APARTMENT', floorArea:1700, amenities:['Pool','Gym','Garden','Security','Parking'], description:'Mega township 3BHK with all amenities. Near NICE road and upcoming metro line.', status:'AVAILABLE' },
  { title:'2BHK in Vijayanagar', city:'Bangalore', area:'Vijayanagar', address:'RPC Layout, Vijayanagar', rent:18000, deposit:54000, bedrooms:2, bathrooms:1, furnished:'UNFURNISHED', propertyType:'APARTMENT', floorArea:880, amenities:['Parking','Security','Borewell'], description:'Affordable unfurnished 2BHK in Vijayanagar. Near Chord Road metro station.', status:'AVAILABLE' },
  { title:'Studio in Cunningham Road', city:'Bangalore', area:'Cunningham Road', address:'Near Leela Palace, Cunningham Road', rent:22000, deposit:44000, bedrooms:1, bathrooms:1, furnished:'FURNISHED', propertyType:'STUDIO', floorArea:450, amenities:['AC','Gym','Security','Concierge'], description:'Boutique studio in Bangalore\'s business district. Steps from UB City mall.', status:'RENTED' },
  { title:'4BHK in Nagarbhavi', city:'Bangalore', area:'Nagarbhavi', address:'BDA Layout, Nagarbhavi', rent:32000, deposit:96000, bedrooms:4, bathrooms:3, furnished:'UNFURNISHED', propertyType:'INDEPENDENT_HOUSE', floorArea:2000, amenities:['Parking','Garden','Terrace','Borewell'], description:'Spacious independent house near NIMHANS and BU campus. Large compound.', status:'AVAILABLE' },
  { title:'2BHK near Malls in Malleshwaram', city:'Bangalore', area:'Malleshwaram', address:'15th Cross, Malleshwaram', rent:24000, deposit:72000, bedrooms:2, bathrooms:2, furnished:'SEMI_FURNISHED', propertyType:'APARTMENT', floorArea:1020, amenities:['Lift','Security','Parking','Power Backup'], description:'Old Bangalore charm with modern comfort. Walking distance to Orion Mall.', status:'AVAILABLE' },
  { title:'1BHK in Doddakammanahalli', city:'Bangalore', area:'Silk Board', address:'Near Silk Board Junction', rent:14500, deposit:43500, bedrooms:1, bathrooms:1, furnished:'FURNISHED', propertyType:'APARTMENT', floorArea:500, amenities:['Wi-Fi','AC','Security'], description:'Budget 1BHK near Silk Board. Easy commute to Electronic City and Koramangala.', status:'AVAILABLE' },
  { title:'3BHK in Kundanahalli', city:'Bangalore', area:'Kundanahalli', address:'BEML Layout, Kundanahalli', rent:40000, deposit:120000, bedrooms:3, bathrooms:3, furnished:'FURNISHED', propertyType:'APARTMENT', floorArea:1800, amenities:['Pool','Gym','Security','Parking','Wi-Fi'], description:'Upscale 3BHK in the golden corridor between Whitefield and Marathahalli.', status:'AVAILABLE' },
  { title:'PG in Domlur', city:'Bangalore', area:'Domlur', address:'Domlur Layout, Near HAL', rent:10000, deposit:20000, bedrooms:1, bathrooms:1, furnished:'FURNISHED', propertyType:'PG', floorArea:260, amenities:['Wi-Fi','Meals','Laundry'], description:'Clean PG near HAL Airport Road. Ideal for aviation and hospitality professionals.', status:'AVAILABLE' },
];

module.exports = { users, properties, IMG };
