const puppeteer = require('puppeteer');
const cloudinary = require('cloudinary').v2;

const generatePdf = async (agreementText, meta) => {
  const browser = await puppeteer.launch({ headless: 'new', args: ['--no-sandbox', '--disable-setuid-sandbox'] });
  const page = await browser.newPage();

  const htmlContent = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <style>
    body { font-family: 'Times New Roman', serif; font-size: 12pt; line-height: 1.6; color: #1a1a1a; padding: 40px 60px; max-width: 800px; margin: 0 auto; }
    h1 { text-align: center; font-size: 18pt; text-transform: uppercase; letter-spacing: 2px; border-bottom: 2px solid #1A56DB; padding-bottom: 12px; margin-bottom: 24px; }
    .meta { text-align: center; color: #555; font-size: 10pt; margin-bottom: 32px; }
    pre { white-space: pre-wrap; font-family: 'Times New Roman', serif; font-size: 11pt; }
    .footer { border-top: 1px solid #ccc; margin-top: 48px; padding-top: 16px; text-align: center; font-size: 9pt; color: #888; }
    .watermark { position: fixed; bottom: 40px; right: 40px; opacity: 0.06; font-size: 80pt; font-weight: bold; color: #1A56DB; transform: rotate(-30deg); }
  </style>
</head>
<body>
  <div class="watermark">RENTEASE</div>
  <h1>Rental Agreement</h1>
  <div class="meta">Tenant: ${meta.tenant} &nbsp;|&nbsp; Owner: ${meta.owner} &nbsp;|&nbsp; Property: ${meta.property}</div>
  <pre>${agreementText}</pre>
  <div class="footer">Generated by RentEase Platform &bull; rentease.in &bull; This document is computer-generated</div>
</body>
</html>`;

  await page.setContent(htmlContent, { waitUntil: 'networkidle0' });
  const pdfBuffer = await page.pdf({ format: 'A4', printBackground: true, margin: { top: '20mm', bottom: '20mm', left: '15mm', right: '15mm' } });
  await browser.close();
  return pdfBuffer;
};

const uploadPdfToCloudinary = async (pdfBuffer, publicId) => {
  return new Promise((resolve, reject) => {
    const stream = cloudinary.uploader.upload_stream(
      { resource_type: 'raw', folder: 'rentease/agreements', public_id: publicId, format: 'pdf' },
      (err, result) => { if (err) reject(err); else resolve(result.secure_url); }
    );
    stream.end(pdfBuffer);
  });
};

module.exports = { generatePdf, uploadPdfToCloudinary };
